In [1]:
import numpy as np

#### a)

In [3]:
null = np.zeros((10))
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### b) + c)

In [29]:
v = np.arange(10,50)
v_reverse = v[::-1]
print(v)
print(v_reverse)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### d)

In [18]:
np.random.randint(0,8,(3,3))

array([[3, 6, 1],
       [7, 0, 5],
       [3, 5, 5]])

#### f)

In [35]:
v = np.random.randint(0,8,(30))
v_mean = np.mean(v)
print(v_mean)

3.533333333333333


#### g)

In [61]:
def fill_border(vector):
    """
    Fills the edge of 2D array with 1
    """
    n,m = vector.shape
    vector[0,:] = 1
    vector[n-1,:] = 1
    vector[:,m-1] = 1
    vector[:,0] = 1
    
n = 5
m = 10
v = np.zeros((n,m))
fill_border(v)
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### h) + i)

In [120]:
v1 = np.zeros((8,8),dtype=int)
v1[:,1::2][::2] = 1
v1[:,0::2][1::2] = 1

pattern = np.array([[0,1],[1,0]])
v2 = np.tile(pattern,(4,4))

print(v1)
print('')
print(v2)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### j)

In [123]:
z = np.arange(11)
z[3:9] *= -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### k)

In [126]:
z = np.random.random(10)
np.sort(z)


array([0.13311761, 0.16368118, 0.17746719, 0.29251766, 0.62048753,
       0.726069  , 0.73629828, 0.87027105, 0.92878628, 0.99980469])

#### l)

In [128]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


#### m)

In [137]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.view(dtype='float32')
print(Z.dtype)

int32
float32


#### n)

In [197]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
print(C)
print('')
D = C[:,0::2]
print(D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]

[[ 18  24]
 [ 54  78]
 [ 90 132]]
