In [12]:
from scipy import linalg
from scipy import stats
import numpy as np
import pandas as pd

### a), b), c)

In [66]:
A = np.matrix([[1,1,3],[4,5,6],[7,8,9]])
b = np.array([1,2,3])
solution = linalg.solve(A,b)
print(solution)

[ 1.78869265e-16 -1.35693925e-16  3.33333333e-01]


### d)

In [67]:
A.dot(solution) == b

matrix([[ True,  True,  True]])

### e), f)

In [68]:
eig_val, eig_vec = linalg.eig(A)

print('Eigen vector:',eig_vec)
print('Eigen values:',eig_val)


Eigen vector: [[-0.20197582 -0.79613157  0.71023933]
 [-0.52960804 -0.06843759 -0.70020814]
 [-0.82384531  0.60124107  0.07258549]]
Eigen values: [15.85892722+0.j -1.17964678+0.j  0.32071957+0.j]


### g)

In [69]:
inv_A = linalg.inv(A)
det_A = linalg.det(inv_A)
print(inv_A)

[[ 0.5        -2.5         1.5       ]
 [-1.          2.         -1.        ]
 [ 0.5         0.16666667 -0.16666667]]


### h)

In [80]:
norm = linalg.norm(A)
print(norm)
norm = linalg.norm(A,ord=np.inf)
print(norm)
norm = linalg.norm(A,ord='nuc')
print(norm)

16.792855623746664
24.0
18.36360126162635


### a)